### ISSUE TITLE
Unable to override the default 'img/' folder

### ISSUE THREAD

**Issue by cassidoo** [ryanburgess/grunt-unused#3]
My code is very similar to the example:
```
  unused: {
    options: {
      reference: 'js/',
      directory: ['**/*/*.html'],
      days: 30,
      remove: false
    }
  }
```

And my file structure is pretty straightforward, with folders situated like:

```
static/
  build/
  css/
  fonts/
  grunt/
  img/
  js/
```

But for some reason, the task always looks into the `img/` folder rather than the `js/` folder.  Am I missing something?  I know that the `img/` folder is the default, but do I have to do something specific to override that?  If it helps, I'm using [load-grunt-config](https://github.com/firstandthird/load-grunt-config) to organize my tasks.

**Comment by cassidoo** [comment]
The more I play with it, the more it looks like I can't override any of the defaults.

**Comment by tusbar** [comment]
This grunt plugin does not support having multiple tasks.

I believe you have something like

```js
unused: {
    myTask: {
        options: { /* … */ }
    }
}
```

It won’t work, you’ll have to only define the `options` hash:

```js
unused: {
    options: { /* … */ }
}
```

This should be fixed as you can’t have multiple checks.

**Comment by cassidoo** [comment]
I see, thank you!
